let presetTopics: [String] = [
    "hiking",
    "photography",
    "cooking",
    "fiction",
    "weightlifting",
    "yoga",
    "video games",
    "poetry",
    "civics",
    "peaceful protests",
    "creative writing",
    "dive bars",
    "whiskey",
    "vodka",
    "gin",
    "tequila",
    "wine",
    "biking",
    "travel",
    "basketball",
    "movies",
    "sneaker collecting",
    "gardening",
    "dancing",
    "line dancing",
    "space tourism",
    "fishing",
    "graphic design",
    "egalitarianism",
    "open source",
    "white hat hacking",
    "soccer",
    "knitting",
    "crocheting",
    "craft beer",
    "mindfulness",
    "auto repair",
    "auto customization",
    "entrepreneurship",
    "fantasy football",
    "fantasy sports",
    "painting",
    "oil painting",
    "acrylics",
    "watercolor",
    "journaling",
    "journalism",
    "international cuisine",
    "early mornings",
    "night owl",
    "mountain biking",
    "rock climbing",
    "camping",
    "chess",
    "longevity",
    "cannabis",
    "reality tv",
    "musical instruments",
    "privacy rights",
    "guitar",
    "piano",
    "violin",
    "cello",
    "drums",
    "percussion",
    "trombone",
    "saxophone",
    "banjo",
    "bass guitar",
    "clubs",
    "naps",
    "edm",
    "classical music",
    "skiing",
    "cycling",
    "ethics",
    "rap",
    "hip-hop",
    "r&b",
    "soul music",
    "screenwriting",
    "profile comedy",
    "rock music",
    "classic rock",
    "indie music",
    "indie films",
    "directing",
    "portrait photography",
    "blogging",
    "vintage items",
    "foreign languages",
    "golf",
    "surfing",
    "skateboarding",
    "live music",
    "diy projects",
    "marathons",
    "ultra running",
    "endurance racing",
    "jogging",
    "board games",
    "cosplay",
    "baking",
    "desserts",
    "local politics",
    "birdwatching",
    "art galleries",
    "museums",
    "science",
    "martial arts",
    "stand-up comedy",
    "streaming",
    "home improvement",
    "improv",
    "vibe coding",
    "vibe marketing",
    "tennis",
    "web development",
    "artificial intelligence",
    "tabletop games",
    "interior decorating",
    "economics",
    "thrifting",
    "vintage clothing",
    "photo editing",
    "pc gaming",
    "console gaming",
    "handheld gaming",
    "charity events",
    "woodworking",
    "scuba diving",
    "snorkeling",
    "food festivals",
    "content creation",
    "social media influencing",
    "motorsports",
    "motorcycles",
    "motogp",
    "cars",
    "formula 1",
    "mls",
    "premier league",
    "squash",
    "cricket",
    "badminton",
    "nascar",
    "self-improvement",
    "national parks",
    "podcasting",
    "retreats",
    "wellness workshops",
    "trivia",
    "comic books",
    "functional fitness",
    "anime",
    "manga",
    "philosophy",
    "stoicism",
    "urban gardening",
    "hydroponics",
    "ice climbing",
    "spelunking",
    "free diving",
    "free climbing",
    "base jumping",
    "bmx",
    "spear fishing",
    "deep sea fishing",
    "pickleball",
    "mimosas",
    "sewing",
    "fashion design",
    "brunch",
    "beach",
    "djÔøϩing",
    "music production",
    "nfl",
    "nba",
    "nhl",
    "mlb",
    "ncaa football",
    "ncaa basketball",
    "ncaa baseball",
    "ufc",
    "boxing",
    "mental health",
    "animal rescue",
    "volunteering",
    "investing",
    "hedonism",
    "stock markets",
    "real estate",
    "book clubs",
    "coffee shops",
    "metallurgy",
    "esports",
    "theater",
    "glass blowing",
    "community events",
    "wine tastings",
    "darts",
    "billiards",
    "robotics",
    "pets",
    "cultural awareness",
    "streetwear",
    "coin collecting",
    "fitness challenges",
    "digital art",
    "mushrooming",
    "architecture",
    "interior design",
    "ceramics",
    "tailgating",
    "sober living",
    "true crime",
    "poker",
    "card games",
    "home automation",
    "astrology",
    "tarot reading",
    "side hustles",
    "small businesses",
    "social clubs",
    "networking",
    "archery",
    "calligraphy",
    "stand-up paddleboarding",
    "astronomy",
    "cross-stitching",
    "bowling",
    "mixology",
    "fantasy novels",
    "fan fiction",
    "videography",
    "space",
    "parkour",
    "sculpting",
    "christianity",
    "catholicism",
    "islam",
    "judaism",
    "atheism",
    "neurodiversity",
    "anthropology",
    "barbecue",
    "pottery",
    "comic conventions",
    "scavenger hunts",
    "sushi",
    "restaurants",
    "taekwondo",
    "kung fu",
    "brazilian jiu jitsu",
    "muay thai",
    "karate",
    "judo",
    "sambo",
    "cross fit",
    "community outreach",
    "international politics",
    "criminal justice reform",
    "global trade",
    "urban exploration",
    "furniture restoration",
    "public speaking",
    "ice skating",
    "cryptocurrency",
    "escape rooms",
    "abstract art",
    "collectibles",
    "disc golf",
    "blacksmithing",
    "classic cars",
    "festivals",
    "raves",
    "video editing",
    "rock concerts",
    "conceptual art",
    "expressionism",
    "pop art",
    "pop culture",
    "genealogy",
    "3d printing",
    "gymnastics",
    "costume design",
    "paintball",
    "ballet",
    "geocaching",
    "vlogging",
    "film photography",
    "concert photography",
    "minimalism",
    "ux design",
    "historical reenactments",
    "canoeing",
    "kayaking",
    "antique collecting",
    "mushroom farming",
    "farming",
    "metalworking",
    "technology",
    "eco-friendly living",
    "custom jewelry",
    "fine jewelry",
    "lock picking",
    "luxury watches",
    "hypercars",
    "drag racing",
    "puzzles",
    "rugby",
    "ice hockey",
    "solo travel",
    "personal finance",
    "forex",
    "law",
    "casual dating",
    "enm",
    "nontraditional relationships",
    "coffee",
    "event planning",
    "animation",
    "cartoons",
    "embroidery",
    "zumba",
    "hunting",
    "furniture building",
    "carpentry",
    "historical research",
    "snowboarding",
    "drifting",
    "outdoor photography",
    "paranormal investigation",
    "water polo",
    "trail running",
    "book collecting",
    "axe throwing",
    "rowing",
    "larping",
    "equestrian",
    "horses",
    "dogs",
    "cats",
    "beekeeping",
    "veganism",
    "vegetarianism",
    "high fashion",
    "mobile app development",
    "meditation",
    "wood carving",
    "fencing",
    "vinyl records",
    "pilates",
    "crafts",
    "swimming",
    "fitness coaching",
    "healthy living",
    "mountain climbing",
    "nfts",
    "bouldering",
    "aviation",
    "helicopters",
    "skydiving",
    "costuming",
    "mythology",
    "ballroom dancing",
    "water sports",
    "roller skating",
    "tea",
    "candle making",
    "drones",
    "historical fiction",
    "leatherwork",
    "charities",
    "ya novels",
    "marvel universe",
    "dc universe",
    "horror films",
    "foreign cinema",
    "shopping",
    "mentoring",
    "psychology",
    "social justice reform",
    "therapy",
    "aa/na"
]

